[build]
  functions = "netlify/functions"
  command = "npm ci && cp -r views netlify/functions/views && cp -r public netlify/functions/public" 

[functions]
  included_files = ["netlify/functions/views/**", "netlify/functions/public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200